"""
api.py

REST API that serves the trained model as a /predict endpoint,
using FastAPI.

Run locally:
    pip install fastapi uvicorn joblib scikit-learn
    uvicorn api:app --reload

Then test with:
    curl -X POST http://127.0.0.1:8000/predict \
        -H "Content-Type: application/json" \
        -d '{"sepal_length": 5.1, "sepal_width": 3.5, "petal_length": 1.4, "petal_width": 0.2}'

Interactive docs (auto-generated by FastAPI) available at:
    http://127.0.0.1:8000/docs
"""

import json
import logging
from datetime import datetime, timezone

import joblib
import numpy as np
from fastapi import FastAPI
from pydantic import BaseModel

# --- Setup ---------------------------------------------------------------

app = FastAPI(title="Iris Classifier API")

# Load trained pipeline once at startup (not per-request)
bundle = joblib.load("model.joblib")
pipeline = bundle["pipeline"]
target_names = bundle["target_names"]
feature_names = bundle["feature_names"]

with open("baseline_stats.json") as f:
    baseline_stats = json.load(f)

# Simple prediction log used for monitoring (see monitoring_analysis.md).
# In a real production system this would go to a proper logging/metrics
# system (e.g. a database, Prometheus, or a cloud logging service)
# instead of a local file.
logging.basicConfig(
    filename="prediction_log.jsonl",
    level=logging.INFO,
    format="%(message)s",
)
logger = logging.getLogger("prediction_logger")


# --- Request/response schema ----------------------------------------------

class IrisFeatures(BaseModel):
    sepal_length: float
    sepal_width: float
    petal_length: float
    petal_width: float


class PredictionResponse(BaseModel):
    predicted_class: str
    confidence: float
    class_probabilities: dict


# --- Routes ----------------------------------------------------------------

@app.get("/")
def health_check():
    """Basic health check endpoint."""
    return {"status": "ok", "model": "iris-logistic-regression"}


@app.post("/predict", response_model=PredictionResponse)
def predict(features: IrisFeatures):
    # Build input in the exact column order the pipeline was trained on
    X = np.array([[
        features.sepal_length,
        features.sepal_width,
        features.petal_length,
        features.petal_width,
    ]])

    probabilities = pipeline.predict_proba(X)[0]
    pred_idx = int(np.argmax(probabilities))
    predicted_class = target_names[pred_idx]
    confidence = float(probabilities[pred_idx])

    class_probabilities = {
        target_names[i]: float(p) for i, p in enumerate(probabilities)
    }

    # Log every prediction with a timestamp and the input features.
    # This log is what a monitoring job would later read to check for
    # data drift and track confidence trends over time.
    log_entry = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "input": features.dict(),
        "predicted_class": predicted_class,
        "confidence": confidence,
    }
    logger.info(json.dumps(log_entry))

    return PredictionResponse(
        predicted_class=predicted_class,
        confidence=confidence,
        class_probabilities=class_probabilities,
    )
